* Fourth attempt

I have installed Haskell Platform again. This time I went to powershell and
executed ~cabal user-config init~ as instructed on Haskell platform website.
Also I added the suggested extra-dirs as the website tells you to do after the
installation.

As an administrator in powershell I ran ~stack setup~.

** Normal use in Powershell
Then, as normal user in powershell I made sure I am in hsudoku folder and
ran ~stack setup~.

After that I ran stack build which gave me a pkg-config error.

Then I ran ~stack exec -- pacman -Sy~ which has synchronized msys package
database. That page gave me a clue https://github.com/commercialhaskell/stack/issues/1586

Then I searched for pkg-config and and to do it ran ~stack exec -- pacman -Ss pkg-config~

And installed it by running:
~stack exec -- pacman -S mingw64/mingw-w64-x86_64-pkg-config~

Then I ran ~stack build~ which gave me a gobject-error.

I have installed clutter library hoping it will also install gobject.
~stack exec -- pacman -S mingw64/mingw-w64-x86_64-clutter~

Afterwards, I have ran stack build and got to gobject-introspection error.

So I ran ~stack exec -- pacman -S mingw64/mingw-w64-x86_64-gobject-introspection~

Compiling continued for a while until I got to gir errors.

So I set up an environment variable for the duration of the powershell session.
#+BEGIN_EXAMPLE
$env:HASKELL_GI_GIR_SEARCH_PATH = "C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\share\gir-1.0"
#+END_EXAMPLE

That worked for a while but then I got an error, so I decided to set other
environment variables.
#+BEGIN_EXAMPLE
$env:XDG_DATA_DIRS="C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\share"
$env:PKG_CONFIG_PATH="C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib\pkgconfig"
#+END_EXAMPLE

Then I tried ~stack build~ again

I made significant progress then I got to this error
https://github.com/NixOS/nixpkgs/issues/16998 .

At which point it was the time to give up.
