* Haskel Install
I have uninstalled everything Haskell related. Also I have removed Haskell
related environment variables and restarted the machine.

I attempted to install HaskellPlatform-8.2.1-full-x86_64-setup.exe by clicking
on the downloaded installer and running it as an administrator.
I got rid of spaces in the path changing the destination folder at the
beginning of the installation to C:\HaskellPlatform

Despite changing the destination folder something strange happened to the
Windows PATH. C:\Program Files\Haskell\bin was prepended to the PATH, but there
is no Haskell folder in Program Files.
C:\HaskellPlatform\mingw\bin was appended to the PATH and it contains ghci and
runhaskell.exe.

Starting WinGHCi from the start menu works.

As a shell I will use mingw64.exe found in C:\HaskellPlatform\msys running it as
an administrator. I did restart the shell as prompted and then ran pacman -Syu.
After breaking the installation at the prompted spot I continued update with
pacman -Su.

Then I installed git running pacman -S git.
And cloned my sample app with git clone https://github.com/bigos/hsudoku.git
ran cd hsudoku and ran onto a problem with stack not being found.

There was stack in C:\Users\Jacek\AppData\Roaming\local\bin but Msys did not
know about it.
Also there is a cabal folder C:\Users\Jacek\AppData\Roaming\cabal that I do not
know if I have removed it prior to my installation.

At this point I had a break.

Later I have added following to ~/.bash_profile
#+BEGIN_EXAMPLE
export PATH="${PATH}:/c/HaskellPlatform/bin:/c/HaskellPlatform/lib/extralibs/bin:/c/Users/Jacek/AppData/Roaming/local/bin:/c/Users/Jacek/AppData/Roaming/cabal/bin"
#+END_EXAMPLE

Now cabal stack and ghci with option --version gave sensible result.
Then I ran
#+BEGIN_EXAMPLE
cabal update
cabal install happy
#+END_EXAMPLE
which ran without errors.

Trying cabal install gave me dependency nightmare, so I switched to stack.
I ran stack setup, which gave me few surprises but completed without errors.
I am unable to scroll back, but I am under inpression that stack has downloaded
another version of msys and another ghci.

At this point I have tried to run stack build and started having dependency
errors. The first error was about pkg-config.
To pull as many dependencies as possible i have tried:
pacman -S mingw64/mingw-w64-x86_64-python3-gobject

Running stack build againg gave me error about pkg-config version so pkg-config
was not installed, so i ran:
pacman -S mingw64/mingw-w64-x86_64-pkg-config

Next error was about gobject-introspection-1.0 so I ran
pacman -S mingw64/mingw-w64-x86_64-gobject-introspection and tried stack build
again

This time I got a linker error
#+BEGIN_EXAMPLE
Linking C:\HaskellPlatform\msys\tmp\stack15648\gi-glib-2.0.14\.stack-work\dist\ca59d0ab\setup\setup.exe ...
Did not find a GI repository for GLib-2.0 in ["C:\\Program Files\\gir-1.0"].
CallStack (from HasCallStack):
error, called at lib\Data\GI\GIR\Repository.hs:89:20 in
haskell-gi-0.20.3-ApJPztkUy0UEBeqlBJz1Ty:Data.GI.GIR.Repository
#+END_EXAMPLE
Luckily https://github.com/haskell-gi/haskell-gi/issues/36 provides a clue.
A quick search on file system reveals gir files in
C:\HaskellPlatform\msys\mingw64\share\gir-1.0.

so I tired following
#+BEGIN_EXAMPLE
HASKELL_GI_GIR_SEARCH_PATH='/c/HaskellPlatform/msys/mingw64/share/gir-1.0' stack build
#+END_EXAMPLE

which has helped me to go past the git errors and gave me another error
#+BEGIN_EXAMPLE
Failed to load shared library 'libcairo-gobject-2.dll'
#+END_EXAMPLE

The library can be found in C:\HaskellPlatform\msys\mingw64\bin so I will try to
set extra-lib-dirs in stack.yaml

#+BEGIN_EXAMPLE
extra-lib-dirs:
- C:\HaskellPlatform\msys\mingw64\bin
#+END_EXAMPLE

This time the extra-lib-dirs that I have added are not garbled as in Haskell
install where Destination folder had spaces.

last error was
#+BEGIN_EXAMPLE
$ HASKELL_GI_GIR_SEARCH_PATH='/c/HaskellPlatform/msys/mingw64/share/gir-1.0' stack build
gi-cairo-1.0.14: configure
gi-gobject-2.0.15: download
gi-gobject-2.0.15: configure
gi-gobject-2.0.15: build
gi-gobject-2.0.15: copy/register

--  While building package gi-cairo-1.0.14 using:
      C:\HaskellPlatform\msys\tmp\stack15372\gi-cairo-1.0.14\.stack-work\dist\ca59d0ab\setup\setup --builddir=.stack-work\dist\ca59d0ab configure --with-ghc=C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --with-ghc-pkg=C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\a3af6af0\pkgdb --libdir=C:\sr\snapshots\a3af6af0\lib --bindir=C:\sr\snapshots\a3af6af0\bin --datadir=C:\sr\snapshots\a3af6af0\share --libexecdir=C:\sr\snapshots\a3af6af0\libexec --sysconfdir=C:\sr\snapshots\a3af6af0\etc --docdir=C:\sr\snapshots\a3af6af0\doc\gi-cairo-1.0.14 --htmldir=C:\sr\snapshots\a3af6af0\doc\gi-cairo-1.0.14 --haddockdir=C:\sr\snapshots\a3af6af0\doc\gi-cairo-1.0.14 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=containers=containers-0.5.7.1 --dependency=haskell-gi=haskell-gi-0.20.3-ApJPztkUy0UEBeqlBJz1Ty --dependency=haskell-gi-base=haskell-gi-base-0.20.4-8bgvGsrBAnN4qbnkM5wOEG --dependency=haskell-gi-overloading=haskell-gi-overloading-1.0-27QuWHK6oxK6ozcekEpmYe --dependency=text=text-1.2.2.2-9UQZjEJZQFSGMffj1Z5g00 --dependency=transformers=transformers-0.5.2.0 --extra-include-dirs=C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C:\HaskellPlatform\msys\mingw64\bin --extra-lib-dirs=C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin --extra-lib-dirs=C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\HaskellPlatform\msys\home\Jacek\hsudoku\.stack-work\logs\gi-cairo-1.0.14.log

    [1 of 2] Compiling Main             ( C:\HaskellPlatform\msys\tmp\stack15372\gi-cairo-1.0.14\Setup.hs, C:\HaskellPlatform\msys\tmp\stack15372\gi-cairo-1.0.14\.stack-work\dist\ca59d0ab\setup\Main.o )
    [2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\HaskellPlatform\msys\tmp\stack15372\gi-cairo-1.0.14\.stack-work\dist\ca59d0ab\setup\StackSetupShim.o )
    Linking C:\HaskellPlatform\msys\tmp\stack15372\gi-cairo-1.0.14\.stack-work\dist\ca59d0ab\setup\setup.exe ...
    Could not resolve symbol "cairo_gobject_context_get_type" in namespace "cairo"
    CallStack (from HasCallStack):
    error, called at lib\Data\GI\CodeGen\LibGIRepository.hs:167:8 in
    haskell-gi-0.20.3-ApJPztkUy0UEBeqlBJz1Ty:Data.GI.CodeGen.LibGIRepository

    ** (setup.exe:20792): WARNING **: Failed to load shared library 'libcairo-gobject-2.dll' referenced by the typelib: 'libcairo-gobject-2.dll': The specified procedure could not be found.
#+END_EXAMPLE

After another break I have modified PATH in ~/.bash_profile to look as follows:
#+BEGIN_EXAMPLE
export PATH="/c/HaskellPlatform/bin:/c/HaskellPlatform/lib/extralibs/bin:/c/Users/Jacek/AppData/Roaming/local/bin:/c/Users/Jacek/AppData/Roaming/cabal/bin:${PATH}"
#+END_EXAMPLE

Installed pango: pacman -S mingw64/mingw-w64-x86_64-pango
and tried again.

Installed another package with pacman -S mingw64/mingw-w64-x86_64-atk
Installed another package with pacman -S mingw64/mingw-w64-x86_64-gdk-pixbuf2

Added following in the hsudoku/stack.yaml
#+BEGIN_EXAMPLE
extra-include-dirs:
- C:\HaskellPlatform\msys\mingw64\include
#+END_EXAMPLE

Tried to ad following environment variables to ~/.bash_profile
#+BEGIN_EXAMPLE
export XDG_DATA_DIRS="/c/HaskellPlatform/msys/mingw64/share"
export PKG_CONFIG_PATH="/c/HaskellPlatform/msys/mingw64/lib/pkgconfig"
export HASKELL_GI_GIR_SEARCH_PATH="/c/HaskellPlatform/msys/mingw64/share/gir-1.0"
#+END_EXAMPLE

These seem to work but I get the warnings saying Failed to load shared library.
Changing the order of PATH elements did not work.

Added following to extra-lib-dirs in stack.yaml
#+BEGIN_EXAMPLE
- C:\HaskellPlatform\msys\mingw64\lib
#+END_EXAMPLE

Gave up on hsudoku because I did not know how to understand this page:
https://github.com/NixOS/nixpkgs/issues/16998

And tried to build the following:
https://github.com/chris-martin/haskell-gtk-hello-world

Got the error about something gtk missing so i tried to install version 2 of
gtk library: pacman -S mingw64/mingw-w64-x86_64-gtk2

After that stack build has worked and I was able to launch the built examples
from the command line.

** Still to do
I need to figure out where shold I put my stack global configuration for

#+BEGIN_EXAMPLE
# Extra directories used by stack for building
extra-include-dirs:
- C:\HaskellPlatform\msys\mingw64\include
extra-lib-dirs:
- C:\HaskellPlatform\msys\mingw64\bin
- C:\HaskellPlatform\msys\mingw64\lib
#+END_EXAMPLE

** Used environment variables

#+BEGIN_EXAMPLE
export XDG_DATA_DIRS="/c/HaskellPlatform/msys/mingw64/share"
export PKG_CONFIG_PATH="/c/HaskellPlatform/msys/mingw64/lib/pkgconfig"
export HASKELL_GI_GIR_SEARCH_PATH="/c/HaskellPlatform/msys/mingw64/share/gir-1.0"

export PATH="${PATH}:/c/HaskellPlatform/bin:/c/HaskellPlatform/lib/extralibs/bin:/c/Users/Jacek/AppData/Roaming/local/bin:/c/Users/Jacek/AppData/Roaming/cabal/bin"
#+END_EXAMPLE

** Stack configuration
https://docs.haskellstack.org/en/stable/yaml_configuration/

** installed packages
#+BEGIN_EXAMPLE
mingw64/mingw-w64-x86_64-adwaita-icon-theme 3.26.0-1 [installed]
mingw64/mingw-w64-x86_64-atk 2.26.1-1 [installed]
mingw64/mingw-w64-x86_64-bzip2 1.0.6-6 [installed]
mingw64/mingw-w64-x86_64-ca-certificates 20170211-2 [installed]
mingw64/mingw-w64-x86_64-cairo 1.15.6-2 [installed]
mingw64/mingw-w64-x86_64-expat 2.2.3-1 [installed]
mingw64/mingw-w64-x86_64-fontconfig 2.12.6-1 [installed]
mingw64/mingw-w64-x86_64-freeglut 3.0.0-4 [installed]
mingw64/mingw-w64-x86_64-freetype 2.8.1-1 [installed]
mingw64/mingw-w64-x86_64-gcc-libs 7.2.0-1 (mingw-w64-x86_64-toolchain) [installed]
mingw64/mingw-w64-x86_64-gdk-pixbuf2 2.36.11-1 [installed]
mingw64/mingw-w64-x86_64-gettext 0.19.8.1-2 [installed]
mingw64/mingw-w64-x86_64-glib2 2.54.2-1 [installed]
mingw64/mingw-w64-x86_64-gmp 6.1.2-1 [installed]
mingw64/mingw-w64-x86_64-gobject-introspection 1.54.1-1 [installed]
mingw64/mingw-w64-x86_64-gobject-introspection-runtime 1.54.1-1 [installed]
mingw64/mingw-w64-x86_64-graphite2 1.3.10-1 [installed]
mingw64/mingw-w64-x86_64-gtk2 2.24.31-6 [installed]
mingw64/mingw-w64-x86_64-harfbuzz 1.7.1-1 [installed]
mingw64/mingw-w64-x86_64-hicolor-icon-theme 0.15-2 [installed]
mingw64/mingw-w64-x86_64-jasper 2.0.14-1 [installed]
mingw64/mingw-w64-x86_64-libcroco 0.6.12-1 [installed]
mingw64/mingw-w64-x86_64-libffi 3.2.1-4 [installed]
mingw64/mingw-w64-x86_64-libiconv 1.15-1 [installed]
mingw64/mingw-w64-x86_64-libjpeg-turbo 1.5.2-1 [installed]
mingw64/mingw-w64-x86_64-libpng 1.6.34-1 [installed]
mingw64/mingw-w64-x86_64-librsvg 2.40.19-1 [installed]
mingw64/mingw-w64-x86_64-libsystre 1.0.1-3 [installed]
mingw64/mingw-w64-x86_64-libtasn1 4.12-1 [installed]
mingw64/mingw-w64-x86_64-libtiff 4.0.8-1 [installed]
mingw64/mingw-w64-x86_64-libtre-git r128.6fb7206-1 [installed]
mingw64/mingw-w64-x86_64-libwinpthread-git 5.0.0.4850.d1662dc7-1 (mingw-w64-x86_64-toolchain) [installed]
mingw64/mingw-w64-x86_64-libxml2 2.9.6-1 [installed]
mingw64/mingw-w64-x86_64-lzo2 2.10-1 [installed]
mingw64/mingw-w64-x86_64-mpc 1.0.3-2 (mingw-w64-x86_64) [installed]
mingw64/mingw-w64-x86_64-mpfr 3.1.6-1 [installed]
mingw64/mingw-w64-x86_64-ncurses 6.0.20170916-1 [installed]
mingw64/mingw-w64-x86_64-openssl 1.0.2.m-1 [installed]
mingw64/mingw-w64-x86_64-p11-kit 0.23.9-1 [installed]
mingw64/mingw-w64-x86_64-pango 1.40.11-1 [installed]
mingw64/mingw-w64-x86_64-pcre 8.41-1 [installed]
mingw64/mingw-w64-x86_64-pixman 0.34.0-3 [installed]
mingw64/mingw-w64-x86_64-pkg-config 0.29.2-1 (mingw-w64-x86_64-toolchain) [installed]
mingw64/mingw-w64-x86_64-pygobject-devel 3.26.1-1 [installed]
mingw64/mingw-w64-x86_64-python2 2.7.14-2 [installed]
mingw64/mingw-w64-x86_64-python2-beaker 1.8.1-2 [installed]
mingw64/mingw-w64-x86_64-python2-mako 1.0.7-1 [installed]
mingw64/mingw-w64-x86_64-python2-markupsafe 1.0-2 [installed]
mingw64/mingw-w64-x86_64-python3 3.6.3-2 [installed]
mingw64/mingw-w64-x86_64-python3-cairo 1.15.3-1 [installed]
mingw64/mingw-w64-x86_64-python3-gobject 3.26.1-1 [installed]
mingw64/mingw-w64-x86_64-readline 7.0.003-1 [installed]
mingw64/mingw-w64-x86_64-shared-mime-info 1.9-1 [installed]
mingw64/mingw-w64-x86_64-sqlite3 3.20.0-1 [installed]
mingw64/mingw-w64-x86_64-tcl 8.6.7-1 [installed]
mingw64/mingw-w64-x86_64-termcap 1.3.1-2 [installed]
mingw64/mingw-w64-x86_64-tk 8.6.7-1 [installed]
mingw64/mingw-w64-x86_64-wineditline 2.201-1 [installed]
mingw64/mingw-w64-x86_64-xz 5.2.3-1 [installed]
mingw64/mingw-w64-x86_64-zlib 1.2.11-1 [installed]
#+END_EXAMPLE

** discovery
Following directory contained a msys installation that haskell was using in the build

C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin
