* Second Attempt
After running into unresolved problem I decided to start all over.
I have uninstalled Haskell Platform and made sure that no residue files or
environment variables are left.

I have noticed that stack creates own version of MSYS which lies on a path
without spaces and is used in compilation. So possibly I could install project
specific external libraries there.

** New install
I have installe HaskellPlatform-8.2.1-full-x86_64-setup.exe to:
C:\Program Files\Haskell Platform\8.2.1
and used all default values.
Stack was installed to C:\Users\Jacek\AppData\Roaming\local\bin

*** Environment variables
That adds system-wide environment variables

C:\Program Files\Haskell\bin;
C:\Program Files\Haskell Platform\8.2.1\lib\extralibs\bin;
C:\Program Files\Haskell Platform\8.2.1\bin;
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\Lenovo\FusionEngine;
C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Lenovo\Bluetooth Software\;
C:\Program Files\Lenovo\Bluetooth Software\syswow64;
C:\Program Files (x86)\Lenovo\Motion Control\;
C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;
C:\Users\Jacek\.dnx\bin;
C:\Program Files\Microsoft DNX\Dnvm\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Program Files (x86)\Skype\Phone\;
C:\Program Files\Steel Bank Common Lisp\1.3.18\;
C:\Program Files\Git\cmd;
C:\Users\Jacek\LocalPrograms\Emacs\emacs-25.3-x86_64\bin;
C:\Program Files\Haskell Platform\8.2.1\mingw\bin;

Note mingw\bin being last that might solve that install problem encountered
during the first attempt.

C:\Users\Jacek\AppData\Roaming\cabal\bin;
C:\Users\Jacek\AppData\Roaming\local\bin;
C:\RailsInstaller\Ruby2.3.0\bin;
C:\Users\Jacek\AppData\Local\Microsoft\WindowsApps


*** Important discovery
If I use regular powershell or windows cmd and go to AppData/Roaming/local/bin
and run stack I can get access to all the environment I might need using
~stcak path~ and ~stack exec env~. These commands give me information about the
environment.


*** Stack msys
At this point I have a path containing msys
C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512

I create a desktop shortuct for easier use by right clicking on:
mingw64_shell.bat

Msys terminal that opens when clicking on the shortcut has very interesting $PATH.

I have updated the msys environment running pacman -Syu.

*** break and another attempt
time for rest

*** After the break full reinstall

In powershell terminal I ran stack exec env and it has created the
C:\sr folder for me.

stack setup is going to polulate
C:\Users\Jacek\AppData\Local\Programs\stack\x86_64-windows\
